// <auto-generated />
using Lojinha.Coupon.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lojinha.Coupon.API.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231222234148_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Lojinha.Coupon.API.Entities.Coupon", b =>
                {
                    b.Property<long>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("coupon_code");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT")
                        .HasColumnName("discount");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1L,
                            CouponCode = "CUPOM-5",
                            Discount = 5m
                        },
                        new
                        {
                            CouponId = 2L,
                            CouponCode = "CUPOM-10",
                            Discount = 10m
                        },
                        new
                        {
                            CouponId = 3L,
                            CouponCode = "CUPOM-15",
                            Discount = 15m
                        },
                        new
                        {
                            CouponId = 4L,
                            CouponCode = "CUPOM-20",
                            Discount = 20m
                        },
                        new
                        {
                            CouponId = 5L,
                            CouponCode = "CUPOM-25",
                            Discount = 25m
                        },
                        new
                        {
                            CouponId = 6L,
                            CouponCode = "CUPOM-30",
                            Discount = 30m
                        },
                        new
                        {
                            CouponId = 7L,
                            CouponCode = "CUPOM-35",
                            Discount = 35m
                        },
                        new
                        {
                            CouponId = 8L,
                            CouponCode = "CUPOM-40",
                            Discount = 40m
                        },
                        new
                        {
                            CouponId = 9L,
                            CouponCode = "CUPOM-45",
                            Discount = 45m
                        },
                        new
                        {
                            CouponId = 10L,
                            CouponCode = "CUPOM-50",
                            Discount = 50m
                        },
                        new
                        {
                            CouponId = 11L,
                            CouponCode = "CUPOM-55",
                            Discount = 55m
                        },
                        new
                        {
                            CouponId = 12L,
                            CouponCode = "CUPOM-60",
                            Discount = 60m
                        },
                        new
                        {
                            CouponId = 13L,
                            CouponCode = "CUPOM-65",
                            Discount = 65m
                        },
                        new
                        {
                            CouponId = 14L,
                            CouponCode = "CUPOM-70",
                            Discount = 70m
                        },
                        new
                        {
                            CouponId = 15L,
                            CouponCode = "CUPOM-75",
                            Discount = 75m
                        },
                        new
                        {
                            CouponId = 16L,
                            CouponCode = "CUPOM-80",
                            Discount = 80m
                        },
                        new
                        {
                            CouponId = 17L,
                            CouponCode = "CUPOM-85",
                            Discount = 85m
                        },
                        new
                        {
                            CouponId = 18L,
                            CouponCode = "CUPOM-90",
                            Discount = 90m
                        },
                        new
                        {
                            CouponId = 19L,
                            CouponCode = "CUPOM-95",
                            Discount = 95m
                        },
                        new
                        {
                            CouponId = 20L,
                            CouponCode = "CUPOM-100",
                            Discount = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
